# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='blog',
            field=models.ManyToManyField(blank=True, to='blog.Blog'),
        ),
    ]
