# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-15 20:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20171015_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='postname',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='blog',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to='blog.Blog'),
        ),
    ]
