# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_remove_category_blog'),
        ('blog', '0005_auto_20171016_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.ManyToManyField(blank=True, to='category.Category'),
        ),
    ]
